# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 06:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('md5', models.CharField(max_length=50)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_file', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=50)),
                ('gender', models.BooleanField()),
                ('reference_word_sequence', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('slot_names', models.CharField(max_length=1000)),
                ('slot_values', models.CharField(max_length=1000)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelValidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('md5', models.CharField(max_length=50)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
